# Generated by Django 5.1.4 on 2025-07-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=150),
        ),
    ]
