# Generated by Django 5.1.4 on 2025-07-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='persons',
            field=models.CharField(default='', max_length=150),
        ),
    ]
