# Generated by Django 5.1.4 on 2025-07-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0003_alter_check_in_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_in',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
