# Generated by Django 5.1.4 on 2025-07-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0004_check_in_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='pics/')),
                ('image2', models.ImageField(upload_to='pics/')),
                ('image3', models.ImageField(upload_to='pics/')),
                ('image4', models.ImageField(upload_to='pics/')),
                ('image5', models.ImageField(upload_to='pics/')),
                ('image6', models.ImageField(upload_to='pics/')),
                ('image7', models.ImageField(upload_to='pics/')),
                ('image8', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
