# Generated by Django 5.1.4 on 2025-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indexpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default='', max_length=1500)),
                ('title2', models.CharField(default='', max_length=1500)),
                ('title3', models.CharField(default='', max_length=1500)),
                ('title4', models.CharField(default='', max_length=1500)),
                ('title5', models.CharField(default='', max_length=1500)),
                ('title6', models.CharField(default='', max_length=1500)),
                ('title7', models.CharField(default='', max_length=1500)),
                ('title8', models.CharField(default='', max_length=1500)),
                ('title9', models.CharField(default='', max_length=1500)),
                ('title10', models.CharField(default='', max_length=1500)),
                ('title11', models.CharField(default='', max_length=1500)),
            ],
        ),
    ]
