# Generated by Django 5.1.4 on 2025-07-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunWineapp', '0006_indexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='title12',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
